[workspace]
resolver = "2"
members = ["packages/lib", "packages/cli", "packages/wasm"]

[workspace.package]
version = "0.0.3"

[workspace.dependencies]
image = "0.24.3"
image-blp = "1.2.0"
serde = "1.0.204"
thiserror = "2.0.11"