[package]
name = "war3parser-wasm"
edition = "2021"
version.workspace = true

[dependencies]
war3parser = { path = "../lib" }
web-sys = { workspace = true, features = ["ImageData"] }
wasm-bindgen = { workspace = true }
photon-rs = { workspace = true }
