// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FogStyle = { style: number, z_height_start: number, z_height_end: number, density: number, red_tint: number, green_tint: number, blue_tint: number, alpha_value: number, };
