// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ForceData = { flags: number, allied: boolean, shared_victory: boolean, shared_vision: boolean, shared_unit_control: boolean, shared_advanced_unit_control: boolean, player_mask: number, name: string, };
