// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GameVersion = { "RoC": number } | { "TFT": number } | { "Reforged": number } | { "Known": number };
