// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MapSize = "Tiny" | "ExtraSmall" | "Small" | "Medium" | "Large" | "ExtraLarge" | "Huge" | "Epic" | "Legendary" | "Unknown";
