// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlayerData = { player_id: number, player_type: number, player_race: number, fixed_position: number, player_name: string, starting_pos_x: number, starting_pos_y: number, ally_low_priorities: number, ally_high_priorities: number, };
