// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RandomTablePositionType } from "./RandomTablePositionType";
import type { RandomUnitSet } from "./RandomUnitSet";

export type RandomUnitTable = { id: number, name: string, position_types: Array<RandomTablePositionType>, sets: Array<RandomUnitSet>, };
