// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RandomItemSet } from "./RandomItemSet";

export type RandomItemTable = { id: number, name: string, sets: Array<RandomItemSet>, };
