// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Tileset = "Ashenvale" | "Barrens" | "Felwood" | "Dungeon" | "LordaeronFall" | "Underground" | "Icecrown" | "DalaranRuins" | "BlackCitadel" | "LordaeronSummer" | "Northrend" | "Outland" | "VillageFall" | "Village" | "LordaeronWinter" | "Dalaran" | "Cityscape" | "SunkenRuins" | "Known";
