// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpgradeAvailability = { player_availability: number, upgrade_id: string, upgrade_level: number, availability: number, };
