// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FogStyle } from "./FogStyle";
import type { ForceData } from "./ForceData";
import type { GameVersion } from "./GameVersion";
import type { GameVersionCode } from "./GameVersionCode";
import type { MapFlags } from "./MapFlags";
import type { MapSize } from "./MapSize";
import type { PlayerData } from "./PlayerData";
import type { RandomItemTable } from "./RandomItemTable";
import type { RandomUnitTable } from "./RandomUnitTable";
import type { TechAvailability } from "./TechAvailability";
import type { Tileset } from "./Tileset";
import type { UpgradeAvailability } from "./UpgradeAvailability";

export type W3iFile = { version: GameVersion, count_saves: number | null, editor_version: number | null, game_version: GameVersionCode | null, map_name: string, map_author: string, map_description: string, recommended_players: string, camera_bounds: Array<number>, camera_bounds_complements: Array<number>, map_playable_width: number, map_playable_height: number, map_width: number, map_height: number, map_size: MapSize, flags: MapFlags, tileset: Tileset, loading_screen_index: number, custom_loading_screen_model_path: string | null, loading_screen_text: string, loading_screen_title: string, loading_screen_subtitle: string, user_game_dataset: number | null, prologue_screen_path: string | null, prologue_screen_text: string, prologue_screen_title: string, prologue_screen_subtitle: string, fog_style: FogStyle | null, global_weather: number | null, custom_sound_environment: string | null, custom_light_environment_id: string | null, custom_water_red_tint: number | null, custom_water_green_tint: number | null, custom_water_blue_tint: number | null, custom_water_alpha_tint: number | null, script_language: number | null, supported_graphics_modes: number | null, game_data_version: number | null, players: Array<PlayerData>, forces: Array<ForceData>, upgrades: Array<UpgradeAvailability>, techs: Array<TechAvailability>, random_unit_tables: Array<RandomUnitTable>, random_item_tables: Array<RandomItemTable> | null, script_language2: number | null, };
